=== maiteuu/T5E3ML/erronka2-1/XSD/erabiltzaileak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="erabiltzaileak">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="erabiltzaile" type="ErabiltzaileType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="ErabiltzaileType">
    <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="izena" type="xs:string"/>
      <xs:element name="pasahitza" type="xs:string"/>
      <xs:element name="rola" type="RolaType"/>
      <xs:element name="sorrera" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="RolaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="admin"/>
      <xs:enumeration value="guest"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== maiteuu/T5E3ML/erronka2-1/XML/erabiltzaileak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Euskal Eskubaloi Federazioa - Erabiltzaileen XML Datu Basea
  
  Fitxategi honek EEF web guneko erabiltzaileen kudeaketa datuak gordetzen ditu.
  Egitura:
  - id: Erabiltzailearen identifikatzaile bakarra (zenbakizkoa)
  - izena: Erabiltzailearen izena (login erabiltzeko)
  - pasahitza: Erabiltzailearen pasahitza (testu arrunta, hash gabe)
  - rola: Erabiltzailearen rola (admin, moderador, guest)
  - sorrera: Erabiltzailearen sortze data
  
  Rolak:
  - admin: Administratzailea - baimen osoak ditu
  - moderador: Moderatzailea - baimen ertainak ditu
  - guest: Bisitaria - oinarrizko erabiltzailea
  
  Segurtasun oharrak:
  - Pasahitzak testu arruntean gordetzen dira (produkzioan hash erabili behar da)
  - Rolen arabera atzipen kontrolatzen da
  - Saioen kudeaketa localStorage-en egiten da
  
  Schema: ../XSD/erabiltzaileak.xsd
-->
<erabiltzaileak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/erabiltzaileak.xsd">
  <erabiltzaile>
    <id>1</id>
    <izena>admin</izena>
    <pasahitza>admin</pasahitza>
    <rola>admin</rola>
    <sorrera>2024-01-01</sorrera>
  </erabiltzaile>
  <erabiltzaile>
    <id>2</id>
    <izena>moderador</izena>
    <pasahitza>moderador</pasahitza>
    <rola>moderador</rola>
    <sorrera>2024-01-01</sorrera>
  </erabiltzaile>
  <erabiltzaile>
    <id>3</id>
    <izena>guest</izena>
    <pasahitza>guest</pasahitza>
    <rola>guest</rola>
    <sorrera>2024-01-01</sorrera>
  </erabiltzaile>
</erabiltzaileak>
