=== maiteuu/T5E3ML/erronka2-1/XSD/sailkapena-egutegia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sailkapena-egutegia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="egutegi" type="EgutegiType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="EgutegiType">
    <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="izena" type="xs:string"/>
      <xs:element name="data" type="xs:date"/>
      <xs:element name="sailkapena">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="taldea" type="TaldeaType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TaldeaType">
    <xs:sequence>
      <xs:element name="posizioa" type="xs:integer"/>
      <xs:element name="izena" type="xs:string"/>
      <xs:element name="partida" type="xs:integer"/>
      <xs:element name="irabaziak" type="xs:integer"/>
      <xs:element name="galak" type="xs:integer"/>
      <xs:element name="puntuak" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== maiteuu/T5E3ML/erronka2-1/XML/sailkapena-egutegia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Sailkapena gordeak - Registros guardados de clasificaciones/temporadas -->
<sailkapena-egutegia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/sailkapena-egutegia.xsd">
  <egutegi>
    <id>1</id>
    <izena>Denboraldia 2023-2024</izena>
    <data>2024-01-15</data>
    <sailkapena>
      <taldea>
        <posizioa>1</posizioa>
        <izena>Bizkaia</izena>
        <partida>10</partida>
        <irabaziak>8</irabaziak>
        <galak>2</galak>
        <puntuak>18</puntuak>
      </taldea>
      <taldea>
        <posizioa>2</posizioa>
        <izena>Gipuzkoa</izena>
        <partida>10</partida>
        <irabaziak>6</irabaziak>
        <galak>4</galak>
        <puntuak>14</puntuak>
      </taldea>
    </sailkapena>
  </egutegi>
</sailkapena-egutegia>
